spring:
  application:
    name: gateway-server

  cloud:
    gateway:

      routes:
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/account/**
        filters:
        - StripPrefix=1

server:
  port: 8002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8001/eureka

management:
  endpoints:
    jmx.exposure.include: "*"
    web.exposure.include: "*"
  security.enabled: false