spring:
  application:
    name: account-service

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka

server:
  port: 9001
  servlet:
    context-path: /v1
